### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by crystaldust** [crystaldust/rclpy#1]
- [x] Handle `parameters`, `remapping_rules`, `namespace` etc. in `LoadNode` service
- [ ] Confirm how to name the specified node(component), keep the logic same to rclcpp
- [ ] Implement a service to list supported component types(rclpy_components, rclcpp_components) in the component container
